services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    image: ${DOCKER_USERNAME}/ocr:Stag
    container_name: ocr.stag
    ports:
      - "3007:3000"
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - pdf-converter-shared-network

networks:
  pdf-converter-shared-network:
    name: pdf-converter-shared-network
    external: true
