version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pdfconverter:Prod
    container_name: pdfconverter-prod
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - pdf-converter-shared-network

networks:
  pdf-converter-shared-network:
    name: pdf-converter-shared-network
    external: true
